test:
  cd test && rm -rf build && cmake -S . -B build && cmake --build build && build/testrunner

build:
  gcc proxy.c csapp.c parse.c tpool.c sbuf.c -o proxy

run *args:
  ./proxy {{args}}

rerun:
  gcc proxy.c csapp.c parse.c tpool.c sbuf.c -o proxy && ./proxy 5000
